name: android
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^4.0.0
  group_list_view: ^1.1.1
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.19
  http: ^0.13.1
  intl: ^0.19.0

# Configuration de flutter_native_splash
flutter_native_splash:
  color: "#FFFFFF" # Couleur de fond
  #color_dark: "#000000" # Optionnel: couleur pour le mode sombre
  image: assets/Logo_Saada.png # Chemin vers votre logo
  #image_dark: assets/logo_dark.png # Optionnel: logo pour le mode sombre
  
  android_12:
    image: assets/Logo_Saada.png
    icon_background_color: "#FFFFFF"
    
  fullscreen: true
  android: true
  ios: true
  web: false
  
  # Paramètres optionnels
  android_gravity: center
  ios_content_mode: center

# Configuration de flutter_icons
flutter_icons:
  android: "launcher_icons"
  ios: true
  image_path: "assets/Logo_Saada.png"

flutter:
  uses-material-design: true
  assets:
    - assets/